### ISSUE TITLE
How to add data to experience to work the same way as on Frontend part?

### ISSUE THREAD

**Issue by illialaz** [convertcom/javascript-sdk#103]
Hello. I've started a runExperience function, and I can see that it passes A/B test on convertcom. But it doesn't set the data as it's working on FE part, the data like Browser, Device, Sources, Campaign, Visitor type, Country. Could you help me with this? Also I want to understand how to configure Custom segmentation on BE.

**Comment by abbaseya** [comment]
@illialaz  you need to implement your own `dataStore` for retaining these data. here is an [example](https://github.com/convertcom/javascript-sdk/tree/main/packages/js-sdk#provide-persistent-datastore).

**Comment by illialaz** [comment]
@abbaseya  I add dataStore object like in the example, but nothing changed. Do you have an example on how to add all the data. I created dataStore object, but which data to set? Should it work automatically when I just create a dataStore object?
![Screenshot 2024-03-04 at 11 54 18](https://github.com/convertcom/javascript-sdk/assets/47160995/594ec6f1-ad10-420e-b69b-043e2e732cf9)

**Comment by abbaseya** [comment]
@illialaz  that's different, the SDK does not auto-collect visitors segments. That's expected to be provided either:
1. By passing a second argument to [createContext()](https://github.com/convertcom/javascript-sdk/tree/main/packages/js-sdk#create-user-context)
2. By using [setDefaultSegments()](https://github.com/convertcom/javascript-sdk/tree/main/packages/js-sdk#set-default-segments)

**Comment by illialaz** [comment]
Yeah, I understood that I need to pass the second argument to createContext(), but to you have some guide on how to send the exact data as you send on the FE part? I have only HTTP Request (Next Request) object
What I found on BE is just possible values for data provided on createContext()
This is for browser type
![Screenshot 2024-03-04 at 12 47 29](https://github.com/convertcom/javascript-sdk/assets/47160995/da3088c6-1870-4758-af5e-a80f0f92fab9)
This is for device type
![Screenshot 2024-03-04 at 12 47 55](https://github.com/convertcom/javascript-sdk/assets/47160995/f66ca0bb-7fca-4a08-9d84-6c7bc184e503)
This is for source type
![Screenshot 2024-03-04 at 12 48 44](https://github.com/convertcom/javascript-sdk/assets/47160995/333e98d5-ef39-4b31-80fb-891536f52b77)
This is for visitor type
![Screenshot 2024-03-04 at 12 49 03](https://github.com/convertcom/javascript-sdk/assets/47160995/f0e1fcb1-75ee-44b6-881c-8bea7d1144af)

**Comment by illialaz** [comment]
@abbaseya Could you help me with this?

**Comment by abbaseya** [comment]
@illialaz my apologies for the delay, you can find the reference under `Send Tracking` > Request Body > `visitors` > `segments` at https://api.convert.com/doc/serving/#tag/Experiences-Tracking/operation/sendTrackingEvents

**Comment by abbaseya** [comment]
@illialaz Side note on `Custom Segments`: they represent Audiences of type `segmentation` which have rules. 
These should be evaluated using [runCustomSegments](https://github.com/convertcom/javascript-sdk/tree/main/packages/js-sdk#run-custom-segments). The SDK shall auto-include those when sending the tracking events.
