### ISSUE TITLE
ConvertSDK connection fails due to CORS Header Policy for 'content-type'

### ISSUE THREAD

**Issue by sb-chericks** [convertcom/javascript-sdk#136]
## The Problem

When the sdk object is constructed, it experiences a CORS error. I am not sure if I am missing some SDK configuration setting, or some setting needs to be established in the Convert Project Portal.

Additionally, in an effort to find a working example of this code for react, I cloned this repo and attempted to run the project in `packages/demo-react`, however the app will not build due to a webpack error: 

Failed to compile.

Module not found: Error: Can't resolve '@convertcom/js-sdk' in 'C:\Users\chericks\source\repos\javascript-sdk\packages\demo-react\src'
ERROR in ./src/App.js 14:0-44
Module not found: Error: Can't resolve '@convertcom/js-sdk' in 'C:\Users\chericks\source\repos\javascript-sdk\packages\demo-react\src'

## Environment Information

I am adding the Convert SDK to an existing React application.
Browser: Edge & Chrome
SDK Version: 4.0.1 (also tried 3.0.0 and 2.4.1)
hosts file domain mapping: `127.0.0.1 obx-local.sonobelloapps.com`
Convert Project Domains: 'http://obx-local.sonobelloapps.com:3000', 'http://obx-local.sonobelloapps.com'

## Problem Details

Console Log Error:
Access to fetch at 'https://cdn-4.convertexperiments.com/api/v1/config/10042568-10049187' from origin 'http://obx-local.sonobelloapps.com:3000' has been blocked by CORS policy: Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.

Screenshots:
![image](https://github.com/convertcom/javascript-sdk/assets/160796564/6793a55f-ab70-4b65-a68e-084a68a82c57)
![image](https://github.com/convertcom/javascript-sdk/assets/160796564/120fb426-a3dd-44fe-b2ec-aac80953b658)

My React Code:
```
const convertSDK: ConvertInterface = new ConvertSDK({
  sdkKey: EnvironmentConfiguration.convertDotCom.sdkKey
});

const useConvertDotComExperience = () => {
  const [userContext, setUserContext] = useState<ContextInterface | null>(null);
  const [experience, setExperience] = useState<BucketedVariation | null>(null);

  useEffect(() => {
    async function initializeConvertSdk() {
      await convertSDK.onReady();
      const userContext: ContextInterface = convertSDK.createContext(generateGUID(), { country: "US", language: "en" });
      const variation: BucketedVariation = userContext.runExperience(
        EnvironmentConfiguration.convertDotCom.experienceId
      );
      setUserContext(userContext);
      setExperience(variation);
      console.log(userContext, variation);
    }
    initializeConvertSdk();
  }, []);

  return { userContext, experience };
};
```

**Comment by sb-chericks** [comment]
I was able to solve this with some assistance from the convert helpdesk team.
 
 The api key I was using was the incorrect format `${accountId}-${projectId}`.

The correct key format is `${accountId}/${projectId}`. This is important because the api key is actually used as a part of the authentication endpoint path, and without the `/` you hit a different endpoint than is intended and receive an erroneous response.

I was unable to find the documentation for what the API key should be anywhere, and the helpdesk similarly could not point me to any location where it is documented. I originally arrived at my incorrect format by attempting to copy the code from one of the demos.

To the development team, I strongly recommend you add the information to the documentation about how the key is formed to avoid this problem in the future. Additionally, I'd recommend that you reconsider the design choice of allowing the key value to directly control the API path for numerous reasons. Accepting 2 discrete values for the project id and account id, and then combining them within the SDK is the much more straightforward and secure way to do this.

**Comment by abbaseya** [comment]
@sb-chericks good that you have this issue resolved with the help of our support team. You stand correct, we should add information about the API key format. The good news is that you won't have to very soon, as we're working on migrating the format of our API keys, so that you do not have to worry about following a specific format anymore.
