### ISSUE TITLE
Warning - getVisitorProperties not defined in ContextInterface

### ISSUE THREAD

**Issue by danjebs** [convertcom/javascript-sdk#137]
VSCode shows a warning when I try to access `context.getVisitorProperties()`
<img width="793" alt="Screenshot 2024-04-16 at 12 33 07 PM" src="https://github.com/convertcom/javascript-sdk/assets/12756405/85277882-a327-4085-8a6b-7d0c9f9ec0da">

Looking in packages/js-sdk/src/interfaces/context.ts, there is no definition for it.

**Comment by abbaseya** [comment]
@danjebs that's a private method used internally at the Context module, why are you trying to use it directly? can you shed some light one what you're trying to accomplish?

**Comment by danjebs** [comment]
@abbaseya I'm using it to pass the visitorProperties for our own tracking. But if it's the same content as what gets passed into `convertSDK.createContext(visitorId, properties)`, then I don't need to use it - provided it stays the same and does not get mutated by the SDK in any way.

FYI it's in the docs at https://convertcom.github.io/javascript-sdk/Context.html#getVisitorProperties. I know it's all beta, but it isn't marked as internal in any way :)

**Comment by abbaseya** [comment]
@danjebs feel free to re-open this issue if it's still unclear or you have other related questions.
