### ISSUE TITLE
Event batching causes un-predictable behaviour in serverless environments.

### ISSUE THREAD

**Issue by danLDev** [convertcom/javascript-sdk#64]
## Issue
We recently tried to implement the JS-SDK on our NextJS-14/App directory project, and noticed we were dropping views & conversions during testing.

After some digging, it appears this was due to the use of the serverless functions, whereby network requests weren't being flushed before the function ended, and the convert context was destroyed. 

Since these executions are stateless, we have no way to keep the convert context alive.

## Proposed solution
We were able to get around the problem by setting `batch_size` to 1 and `release_interval` 1ms, forcing the batch to flush before our function concluded. 

It would be great if there was a way to manually flush the queue, such as `convertContext.releaseQueue()`, this would allow for an arbitrary batch size which we could flush on demand before returning.

If this solution isn't approved, it should be simple enough to address the via the docs, as currently `events.batch_size` and `events.release_interval` aren't documented.

#### Update to config section mentioning config values:
```javascript
import {LogLevel} from '@convertcom/js-sdk');

const config = {
  sdkKey: '' // either this or 'data' has to be provided
  environment: 'staging',
  logger: {
    logLevel: LogLevel.DEBUG,
    customLoggers: [] // Allows 3rd party loggers to be passed
  },
  dataStore: null, // Allows 3rd party data store to be passed (optional)
  dataRefreshInterval: 300000, // in milliseconds (5 minutes)
  data: projectData,
  events: {
    batch_size: 1, // Maximum batch size before network requests are sent (defaults to 10)
    release_interval: 1, // Release batch at intervals regardless of current batch size (milliseconds, defaults to 10000)
  },
  network: {
    tracking: true, // can be set to false to disable tracking events
    cacheLevel: 'default' // can be set to 'low' for short-lived cache (for development purposes only)
  }
};
```

#### New section mentioning batch behaviour:
```
## Network event batching

In order to prevent an un-necessary number of network calls, network requests resulting from `userContext.runExperience` and `userContext.trackConversion` are batched and flushed at regular intervals.

This can cause issues when working in a serverless/edge environment, where the duration of the runtime may not exceed the release interval. This can result in dropped views/conversions.

In order to avoid this, it is advised to configure a low `events.batch_size` or `events.release_interval`, to ensure event batches are flushed predictably.
```

I'm happy to raise a PR with either of the above solutions if given permission.

**Comment by abbaseya** [comment]
@danLDev Interesting case, and thank you for spotting that one. I'm not sure if it's best to introduce a new context method called `releaseQueue` or simply expose the ApiManager instance altogether, i.e. `userContext.apiManager.releaseQueue()` (_since `releaseQueue` already exposed there separately_). I guess this way one can leverage all exposed methods from various managers within context. Assuming that there might be other scenarios that require other methods to be exposed to context. What do you think?

**Comment by danLDev** [comment]
@abbaseya that sounds sensible to me, it would probably be more maintainable than duplicating the method.

**Comment by abbaseya** [comment]
@danLDev  we're just release version [2.3.0](https://github.com/convertcom/javascript-sdk/releases/tag/js-sdk-v2.3.0) which introduces a new context method `Context.releaseQueues()` (_plural_) that sends all pending API/DataStore queues to server.
