### ISSUE TITLE
Publish pre-release to npm

### ISSUE THREAD

**Issue by mattddean** [convertcom/javascript-sdk#8]
I'm trying to use this library, but am running into various issues. For example, I get these module resolution issues:

```
@acme/nextjs:dev: Module not found: Can't resolve 'http' in '/Users/user/static/org/company/website/node_modules/.pnpm/@convertcom+js-sdk@1.2.0/node_modules/@convertcom/js-sdk/lib'

@acme/nextjs:dev: Module not found: Can't resolve 'https' in '/Users/user/static/org/company/website/node_modules/.pnpm/@convertcom+js-sdk@1.2.0/node_modules/@convertcom/js-sdk/lib'

@acme/nextjs:dev: Module not found: Can't resolve 'querystring' in '/Users/user/static/org/company/website/node_modules/.pnpm/@convertcom+js-sdk@1.2.0/node_modules/@convertcom/js-sdk/lib'

@acme/nextjs:dev: Module not found: Can't resolve 'querystring' in '/Users/user/static/org/company/website/node_modules/.pnpm/@convertcom+js-sdk@1.2.0/node_modules/@convertcom/js-sdk/lib'
```

As well as this issue:

```
@acme/nextjs:dev: ApiManager.releaseQueue() { error: 'Unable to perform network request' }
```

I have a feeling that all of these issues are fixed on the pre-release-v1.3 branch, and I'd like to try it out. Please publish it to npm under some sort of pre-release or canary tag.

**Comment by abbaseya** [comment]
@mattddean we will publish the release soon enough, are you interested in joining the alpha testing phase?

**Comment by mattddean** [comment]
@abbaseya absolutely

**Comment by abbaseya** [comment]
@mattddean good news, we're going to release these major changes anyway. I'll keep you posted.

**Comment by mattddean** [comment]
@abbaseya that's great news! Any idea of the timeline? We're looking to launch convert.com on our site next week.

**Comment by abbaseya** [comment]
@mattddean we're planning to publish these update by Tuesday.

**Comment by abbaseya** [comment]
@mattddean we've just release v2.0.0, feel free to use it now. One note though, kindly use `yarn` for now. We're working on a more universal installation in the near future.

**Comment by mattddean** [comment]
@abbaseya awesome!
